/*
 * DocStudio Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R121.14
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docstudio.client.model;

import com.docstudio.client.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.*;

/**
 * Account billing address
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-18T14:19:30.369078200+02:00[Europe/Kiev]", comments = "Generator version: 7.10.0")
public class AccountAddressDTO {
  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  @javax.annotation.Nonnull
  private String country;

  public static final String SERIALIZED_NAME_REGION = "region";
  @SerializedName(SERIALIZED_NAME_REGION)
  @javax.annotation.Nonnull
  private String region;

  public static final String SERIALIZED_NAME_COUNTRY_EN = "countryEn";
  @SerializedName(SERIALIZED_NAME_COUNTRY_EN)
  @javax.annotation.Nonnull
  private String countryEn;

  public static final String SERIALIZED_NAME_REGION_EN = "regionEn";
  @SerializedName(SERIALIZED_NAME_REGION_EN)
  @javax.annotation.Nonnull
  private String regionEn;

  public static final String SERIALIZED_NAME_STREET = "street";
  @SerializedName(SERIALIZED_NAME_STREET)
  @javax.annotation.Nonnull
  private String street;

  public static final String SERIALIZED_NAME_STREET2 = "street2";
  @SerializedName(SERIALIZED_NAME_STREET2)
  @javax.annotation.Nullable
  private String street2;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  @javax.annotation.Nonnull
  private String city;

  public static final String SERIALIZED_NAME_ZIP = "zip";
  @SerializedName(SERIALIZED_NAME_ZIP)
  @javax.annotation.Nonnull
  private String zip;

  public static final String SERIALIZED_NAME_FORMATTED_ADDRESS = "formattedAddress";
  @SerializedName(SERIALIZED_NAME_FORMATTED_ADDRESS)
  @javax.annotation.Nonnull
  private String formattedAddress;

  public static final String SERIALIZED_NAME_COUNTRY_I_S_O = "countryISO";
  @SerializedName(SERIALIZED_NAME_COUNTRY_I_S_O)
  @javax.annotation.Nullable
  private String countryISO;

  public AccountAddressDTO() {
  }

  public AccountAddressDTO country(@javax.annotation.Nonnull String country) {
    this.country = country;
    return this;
  }

  /**
   * Country
   * @return country
   */
  @javax.annotation.Nonnull
  public String getCountry() {
    return country;
  }

  public void setCountry(@javax.annotation.Nonnull String country) {
    this.country = country;
  }


  public AccountAddressDTO region(@javax.annotation.Nonnull String region) {
    this.region = region;
    return this;
  }

  /**
   * Region
   * @return region
   */
  @javax.annotation.Nonnull
  public String getRegion() {
    return region;
  }

  public void setRegion(@javax.annotation.Nonnull String region) {
    this.region = region;
  }


  public AccountAddressDTO countryEn(@javax.annotation.Nonnull String countryEn) {
    this.countryEn = countryEn;
    return this;
  }

  /**
   * Country EN
   * @return countryEn
   */
  @javax.annotation.Nonnull
  public String getCountryEn() {
    return countryEn;
  }

  public void setCountryEn(@javax.annotation.Nonnull String countryEn) {
    this.countryEn = countryEn;
  }


  public AccountAddressDTO regionEn(@javax.annotation.Nonnull String regionEn) {
    this.regionEn = regionEn;
    return this;
  }

  /**
   * Region EN
   * @return regionEn
   */
  @javax.annotation.Nonnull
  public String getRegionEn() {
    return regionEn;
  }

  public void setRegionEn(@javax.annotation.Nonnull String regionEn) {
    this.regionEn = regionEn;
  }


  public AccountAddressDTO street(@javax.annotation.Nonnull String street) {
    this.street = street;
    return this;
  }

  /**
   * Street
   * @return street
   */
  @javax.annotation.Nonnull
  public String getStreet() {
    return street;
  }

  public void setStreet(@javax.annotation.Nonnull String street) {
    this.street = street;
  }


  public AccountAddressDTO street2(@javax.annotation.Nullable String street2) {
    this.street2 = street2;
    return this;
  }

  /**
   * Street
   * @return street2
   */
  @javax.annotation.Nullable
  public String getStreet2() {
    return street2;
  }

  public void setStreet2(@javax.annotation.Nullable String street2) {
    this.street2 = street2;
  }


  public AccountAddressDTO city(@javax.annotation.Nonnull String city) {
    this.city = city;
    return this;
  }

  /**
   * City
   * @return city
   */
  @javax.annotation.Nonnull
  public String getCity() {
    return city;
  }

  public void setCity(@javax.annotation.Nonnull String city) {
    this.city = city;
  }


  public AccountAddressDTO zip(@javax.annotation.Nonnull String zip) {
    this.zip = zip;
    return this;
  }

  /**
   * Zip code
   * @return zip
   */
  @javax.annotation.Nonnull
  public String getZip() {
    return zip;
  }

  public void setZip(@javax.annotation.Nonnull String zip) {
    this.zip = zip;
  }


  public AccountAddressDTO formattedAddress(@javax.annotation.Nonnull String formattedAddress) {
    this.formattedAddress = formattedAddress;
    return this;
  }

  /**
   * Formatted address
   * @return formattedAddress
   */
  @javax.annotation.Nonnull
  public String getFormattedAddress() {
    return formattedAddress;
  }

  public void setFormattedAddress(@javax.annotation.Nonnull String formattedAddress) {
    this.formattedAddress = formattedAddress;
  }


  public AccountAddressDTO countryISO(@javax.annotation.Nullable String countryISO) {
    this.countryISO = countryISO;
    return this;
  }

  /**
   * Country ISO code
   * @return countryISO
   */
  @javax.annotation.Nullable
  public String getCountryISO() {
    return countryISO;
  }

  public void setCountryISO(@javax.annotation.Nullable String countryISO) {
    this.countryISO = countryISO;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AccountAddressDTO instance itself
   */
  public AccountAddressDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountAddressDTO accountAddressDTO = (AccountAddressDTO) o;
    return Objects.equals(this.country, accountAddressDTO.country) &&
        Objects.equals(this.region, accountAddressDTO.region) &&
        Objects.equals(this.countryEn, accountAddressDTO.countryEn) &&
        Objects.equals(this.regionEn, accountAddressDTO.regionEn) &&
        Objects.equals(this.street, accountAddressDTO.street) &&
        Objects.equals(this.street2, accountAddressDTO.street2) &&
        Objects.equals(this.city, accountAddressDTO.city) &&
        Objects.equals(this.zip, accountAddressDTO.zip) &&
        Objects.equals(this.formattedAddress, accountAddressDTO.formattedAddress) &&
        Objects.equals(this.countryISO, accountAddressDTO.countryISO)&&
        Objects.equals(this.additionalProperties, accountAddressDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, region, countryEn, regionEn, street, street2, city, zip, formattedAddress, countryISO, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountAddressDTO {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    countryEn: ").append(toIndentedString(countryEn)).append("\n");
    sb.append("    regionEn: ").append(toIndentedString(regionEn)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    street2: ").append(toIndentedString(street2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("    formattedAddress: ").append(toIndentedString(formattedAddress)).append("\n");
    sb.append("    countryISO: ").append(toIndentedString(countryISO)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("country");
    openapiFields.add("region");
    openapiFields.add("countryEn");
    openapiFields.add("regionEn");
    openapiFields.add("street");
    openapiFields.add("street2");
    openapiFields.add("city");
    openapiFields.add("zip");
    openapiFields.add("formattedAddress");
    openapiFields.add("countryISO");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("country");
    openapiRequiredFields.add("region");
    openapiRequiredFields.add("countryEn");
    openapiRequiredFields.add("regionEn");
    openapiRequiredFields.add("street");
    openapiRequiredFields.add("city");
    openapiRequiredFields.add("zip");
    openapiRequiredFields.add("formattedAddress");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AccountAddressDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AccountAddressDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccountAddressDTO is not found in the empty JSON string", AccountAddressDTO.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AccountAddressDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("country").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `country` to be a primitive type in the JSON string but got `%s`", jsonObj.get("country").toString()));
      }
      if (!jsonObj.get("region").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `region` to be a primitive type in the JSON string but got `%s`", jsonObj.get("region").toString()));
      }
      if (!jsonObj.get("countryEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryEn").toString()));
      }
      if (!jsonObj.get("regionEn").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `regionEn` to be a primitive type in the JSON string but got `%s`", jsonObj.get("regionEn").toString()));
      }
      if (!jsonObj.get("street").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `street` to be a primitive type in the JSON string but got `%s`", jsonObj.get("street").toString()));
      }
      if ((jsonObj.get("street2") != null && !jsonObj.get("street2").isJsonNull()) && !jsonObj.get("street2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `street2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("street2").toString()));
      }
      if (!jsonObj.get("city").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `city` to be a primitive type in the JSON string but got `%s`", jsonObj.get("city").toString()));
      }
      if (!jsonObj.get("zip").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `zip` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zip").toString()));
      }
      if (!jsonObj.get("formattedAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `formattedAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("formattedAddress").toString()));
      }
      if ((jsonObj.get("countryISO") != null && !jsonObj.get("countryISO").isJsonNull()) && !jsonObj.get("countryISO").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `countryISO` to be a primitive type in the JSON string but got `%s`", jsonObj.get("countryISO").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccountAddressDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccountAddressDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccountAddressDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccountAddressDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<AccountAddressDTO>() {
           @Override
           public void write(JsonWriter out, AccountAddressDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AccountAddressDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             AccountAddressDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AccountAddressDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AccountAddressDTO
   * @throws IOException if the JSON string is invalid with respect to AccountAddressDTO
   */
  public static AccountAddressDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccountAddressDTO.class);
  }

  /**
   * Convert an instance of AccountAddressDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

