/*
 * DocStudio Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R120.10
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docstudio.client.model;

import com.docstudio.client.JSON;
import com.google.gson.*;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.*;

/**
 * StampRequestDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-12-13T14:03:07.416970900+02:00[Europe/Kiev]", comments = "Generator version: 7.10.0")
public class StampRequestDTO {
  public static final String SERIALIZED_NAME_CERTIFICATE = "certificate";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE)
  @javax.annotation.Nonnull
  private byte[] certificate;

  public static final String SERIALIZED_NAME_ENVELOPE_UUID = "envelopeUuid";
  @SerializedName(SERIALIZED_NAME_ENVELOPE_UUID)
  @javax.annotation.Nonnull
  private UUID envelopeUuid;

  public static final String SERIALIZED_NAME_SIGNING_DATE = "signingDate";
  @SerializedName(SERIALIZED_NAME_SIGNING_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime signingDate;

  public StampRequestDTO() {
  }

  public StampRequestDTO certificate(@javax.annotation.Nonnull byte[] certificate) {
    this.certificate = certificate;
    return this;
  }

  /**
   * Get certificate
   * @return certificate
   */
  @javax.annotation.Nonnull
  public byte[] getCertificate() {
    return certificate;
  }

  public void setCertificate(@javax.annotation.Nonnull byte[] certificate) {
    this.certificate = certificate;
  }


  public StampRequestDTO envelopeUuid(@javax.annotation.Nonnull UUID envelopeUuid) {
    this.envelopeUuid = envelopeUuid;
    return this;
  }

  /**
   * Envelope UUID in order to detect language
   * @return envelopeUuid
   */
  @javax.annotation.Nonnull
  public UUID getEnvelopeUuid() {
    return envelopeUuid;
  }

  public void setEnvelopeUuid(@javax.annotation.Nonnull UUID envelopeUuid) {
    this.envelopeUuid = envelopeUuid;
  }


  public StampRequestDTO signingDate(@javax.annotation.Nullable OffsetDateTime signingDate) {
    this.signingDate = signingDate;
    return this;
  }

  /**
   * Signing date
   * @return signingDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSigningDate() {
    return signingDate;
  }

  public void setSigningDate(@javax.annotation.Nullable OffsetDateTime signingDate) {
    this.signingDate = signingDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StampRequestDTO stampRequestDTO = (StampRequestDTO) o;
    return Arrays.equals(this.certificate, stampRequestDTO.certificate) &&
        Objects.equals(this.envelopeUuid, stampRequestDTO.envelopeUuid) &&
        Objects.equals(this.signingDate, stampRequestDTO.signingDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Arrays.hashCode(certificate), envelopeUuid, signingDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StampRequestDTO {\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    envelopeUuid: ").append(toIndentedString(envelopeUuid)).append("\n");
    sb.append("    signingDate: ").append(toIndentedString(signingDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("certificate");
    openapiFields.add("envelopeUuid");
    openapiFields.add("signingDate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("certificate");
    openapiRequiredFields.add("envelopeUuid");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StampRequestDTO
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StampRequestDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in StampRequestDTO is not found in the empty JSON string", StampRequestDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StampRequestDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `StampRequestDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StampRequestDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("envelopeUuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `envelopeUuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("envelopeUuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StampRequestDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StampRequestDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StampRequestDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StampRequestDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<StampRequestDTO>() {
           @Override
           public void write(JsonWriter out, StampRequestDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StampRequestDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StampRequestDTO given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StampRequestDTO
   * @throws IOException if the JSON string is invalid with respect to StampRequestDTO
   */
  public static StampRequestDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StampRequestDTO.class);
  }

  /**
   * Convert an instance of StampRequestDTO to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

