/*
 * DocStudio Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R110.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docstudio.client.api;

import com.docstudio.client.ApiException;
import com.docstudio.client.model.LabelAssociationDTO;
import com.docstudio.client.model.LabelDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.UUID;

/**
 * API tests for LabelControllerApi
 */
@Disabled
public class LabelControllerApiTest {

    private final LabelControllerApi api = new LabelControllerApi();

    /**
     * Assign label to envelopes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void assignmentsTest() throws ApiException {
        UUID mailbox = null;
        LabelAssociationDTO labelAssociationDTO = null;
        api.assignments(mailbox, labelAssociationDTO);
        // TODO: test validations
    }

    /**
     * Save label to DB
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createLabelTest() throws ApiException {
        UUID mailbox = null;
        LabelDTO labelDTO = null;
        LabelDTO response = api.createLabel(mailbox, labelDTO);
        // TODO: test validations
    }

    /**
     * Unassign label from envelopes
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deAssignmentsTest() throws ApiException {
        UUID mailbox = null;
        LabelAssociationDTO labelAssociationDTO = null;
        api.deAssignments(mailbox, labelAssociationDTO);
        // TODO: test validations
    }

    /**
     * Delete label
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteLabelTest() throws ApiException {
        UUID uuid = null;
        UUID mailbox = null;
        api.deleteLabel(uuid, mailbox);
        // TODO: test validations
    }

    /**
     * Retrieve all labels for mailbox for authorized user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        UUID mailbox = null;
        List<LabelDTO> response = api.getAll(mailbox);
        // TODO: test validations
    }

    /**
     * Update label
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateLabelTest() throws ApiException {
        UUID uuid = null;
        UUID mailbox = null;
        LabelDTO labelDTO = null;
        LabelDTO response = api.updateLabel(uuid, mailbox, labelDTO);
        // TODO: test validations
    }

}
