/*
 * DocStudio Api Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: R110.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.docstudio.client.api;

import com.docstudio.client.ApiException;
import com.docstudio.client.model.ConfirmUploadDTO;
import java.io.File;
import com.docstudio.client.model.ImportTaskDTO;
import com.docstudio.client.model.SingleUuidDTO;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UploadControllerApi
 */
@Disabled
public class UploadControllerApiTest {

    private final UploadControllerApi api = new UploadControllerApi();

    /**
     * Cancel import process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelTest() throws ApiException {
        UUID uploadUuid = null;
        api.cancel(uploadUuid);
        // TODO: test validations
    }

    /**
     * Approve import process
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void confirmTest() throws ApiException {
        UUID uploadUuid = null;
        ConfirmUploadDTO confirmUploadDTO = null;
        api.confirm(uploadUuid, confirmUploadDTO);
        // TODO: test validations
    }

    /**
     * Get import processing task
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getImportTaskTest() throws ApiException {
        UUID uploadUuid = null;
        ImportTaskDTO response = api.getImportTask(uploadUuid);
        // TODO: test validations
    }

    /**
     * Upload dictionary file for importing
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void uploadDictionaryTest() throws ApiException {
        UUID dictionaryUuid = null;
        UUID mailbox = null;
        File _file = null;
        SingleUuidDTO response = api.uploadDictionary(dictionaryUuid, mailbox, _file);
        // TODO: test validations
    }

}
